SET SQL_SAFE_UPDATES = 0;
delete from DOMAIN_DATA;
delete from CHANGE_MANAGEMENT_CHANGE_WINDOWS;
delete from CHANGE_MANAGEMENT_RELATED_ASSETS;
delete from CHANGE_MANAGEMENT_SCHEDULES;
delete from CHANGE_MANAGEMENT_GROUPS;
delete from SCHEDULE_APPROVALS;
delete from SCHEDULE_EVENTS;
delete from SCHEDULES;

SET SQL_SAFE_UPDATES = 1;
