version: '3'

services:
  mariadb:
    image: mariadb:10.1.11
    volumes:
      - "/var/lib/mysql"
      - "./mariadb/conf1:/etc/mysql/conf.d:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=beer
    ports:
      - "8806:3306"

  db-init-svc:
    image: onap/optf-cmso-dbinit
    volumes:
      - "./cmso-service/etc:/share/etc:rw"
      - "./cmso-service/logs:/share/logs:rw"
    depends_on:
      - mariadb
    environment: 
      - DB_HOST=mariadb
      - DB_PORT=3306
    entrypoint: "bash -x /share/etc/startDbinitService.sh"

  db-init-opt:
    image: onap/optf-cmso-dbinit
    volumes:
      - "./cmso-optimizer/etc:/share/etc:rw"
      - "./cmso-optimizer/logs:/share/logs:rw"
    depends_on:
      - mariadb
    environment: 
      - DB_HOST=mariadb
      - DB_PORT=3306
    entrypoint: "bash -x /share/etc/startDbinitService.sh"


  cmso-service:
    image: onap/optf-cmso-service
    volumes:
      - "./cmso-service/etc:/share/etc:rw"
      - "./cmso-service/logs:/share/logs:rw"
      - "./cmso-service/debug-logs:/share/debug-logs:rw"
    depends_on:
      - db-init-svc
    entrypoint: "bash -x /share/etc/startJacocoService.sh"
    ports:
      - "8080:8080"
    environment: 
      - DB_HOST=mariadb
      - DB_PORT=3306
      - OPTIMIZER_URL=http://cmso-optimizer:7997/optimizer/v1/optimize/schedule
      - OPTIMIZER_HEALTH_URL=http://cmso-optimizer:7997/optimizer/v1/health?checkInterfaces=true

  cmso-ticketmgt:
    image: onap/optf-cmso-ticketmgt
    volumes:
      - "./cmso-ticketmgt/etc:/share/etc:rw"
      - "./cmso-ticketmgt/logs:/share/logs:rw"
      - "./cmso-ticketmgt/debug-logs:/share/debug-logs:rw"
    entrypoint: "bash -x /share/etc/startJacocoService.sh"
    ports:
      - "7999:7999"

  cmso-topology:
    image: onap/optf-cmso-topology
    volumes:
      - "./cmso-topology/etc:/share/etc:rw"
      - "./cmso-topology/logs:/share/logs:rw"
      - "./cmso-topology/debug-logs:/share/debug-logs:rw"
    entrypoint: "bash -x /share/etc/startJacocoService.sh"
    ports:
      - "7998:7998"

  cmso-optimizer:
    image: onap/optf-cmso-optimizer
    volumes:
      - "./cmso-optimizer/etc:/share/etc:rw"
      - "./cmso-optimizer/logs:/share/logs:rw"
      - "./cmso-optimizer/debug-logs:/share/debug-logs:rw"
    depends_on:
      - db-init-opt
    entrypoint: "bash -x /share/etc/startJacocoService.sh"
    ports:
      - "7997:7997"
    environment: 
      - DB_HOST=mariadb
      - DB_PORT=3306
      - TOPOLOGY_HOST=cmso-topology
      - TICKETMGT_HOST=cmso-ticketmgt


  cmso-robot:
    image: onap/optf-cmso-robot
    volumes:
      - "./cmso-robot/logs:/share:rw"
    depends_on:
      - cmso-service
    environment:
      - GLOBAL_SCHEDULER_URL=http://cmso-service:8080
      - GLOBAL_OPTIMIZER_URL=http://cmso-optimizer:7997
      - CMSO_STARTUP_WAIT_TIME=20m
      - TAGS=-i ete -i opt_validation
      - OUTPUT=-d /share
    working_dir: /opt/cmso-robot  
    entrypoint: "bash -x /opt/cmso-robot/ete.sh"

